prettified configs and fixed deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -6,7 +6,7 @@ set -o errexit
 warn () { printf "%s: %s" "$0" "$@" >&2; }
 die () { rc=$1; shift; warn "$@"; exit "$rc"; }
 
-npm install -g jq || die "Could not install jq."
+[ -x "$(command -v jq)" ] || npm install -g jq || die "Could not install jq."
 
 [ -z "$BEARER_TOKEN" ]     && die "Token \$BEARER_TOKEN undefined!";
 [ -z "$SSH_DEPLOY_HOSTS" ] && die "Deploy servers (\$SSH_DEPLOY_HOSTS) undefined!";
@@ -15,7 +15,7 @@ npm install -g jq || die "Could not install jq."
 
 workingDir=$(pwd)
 targetDir="platforms/browser/www/"
-deployDir="deploy"
+deployDir="deploy.d"
 configDir="configs"
 
 # Prepare different versions for different configs
@@ -27,11 +27,11 @@ configDir="configs"
 mkdir "$deployDir"
 for config in "$configDir"/*.config.dist.json; do
   # set token in config
-  jq ".api.authorization=\"$BEARER_TOKEN\"" > "$config.temp" || die "Could not set \$BEARER_TOKEN in $config."
+  jq ".api.authorization=\"$BEARER_TOKEN\"" "$config" > "$config.temp" || die "Could not set \$BEARER_TOKEN in $config."
   mv "$config.temp" "$config"
 
   # derive name of this deploy from config file name
-  configName=$(echo "$config" | cut -d '.' -f 1) # haus-X.config.dist.json -> haus-X
+  configName=$(echo "${config##*/}" | cut -d '.' -f 1) # haus-X.config.dist.json -> haus-X
 
   # create subdirectory for this version and descend into it
   deploySubDir="$deployDir/$configName"
@@ -39,7 +39,7 @@ for config in "$configDir"/*.config.dist.json; do
   cd "$deploySubDir"
 
   # copy files over
-  cp --link --recursive "$targetDir" .
+  cp --link --recursive "$workingDir/$targetDir" .
 
   # clone corresponding branch of ads repo to destination if ADS_REPO_URL is set
   if [ -n "$ADS_REPO_URL" ]; then
@@ -48,13 +48,14 @@ for config in "$configDir"/*.config.dist.json; do
     # if ads dir is non existent or empty we disable ads-page by removing the ads-config-element
     if [ ! -d assets/ads ] || [ -z "$(ls -A assets/ads)" ]; then
       warn "Ads directory is empty. Disabling ads page."
-      jq ".ads.disabled=true" "$config" > "$config.temp" || die "Could not disable ads-page."
-      mv "$config.temp" "$config" || die "Could not disable ads-page."
+      jq ".ads.disabled=true" "$workingDir/$config" > "$workingDir/$config.temp" || die "Could not disable ads-page."
+      mv "$workingDir/$config.temp" "$workingDir/$config" || die "Could not disable ads-page."
     fi
   fi
 
   # copy corresponding config over
-  cp --link "$config" assets/config.json
+  echo "$workingDir/$config" "$workingDir/$deploySubDir/www/assets/config.json"
+  cp --link "$workingDir/$config" "$workingDir/$deploySubDir/www/assets/config.json"
 
   cd "$workingDir"
 done
@@ -62,5 +63,5 @@ done
 # deploy to servers
 cd "$deployDir"
 for server in $SSH_DEPLOY_HOSTS; do
-    tar cfz - ./* | ssh -i /root/.ssh/id_rsa "gitup-deploy@$server";
+    tar cfz - ./* > d # | ssh -i /root/.ssh/id_rsa "gitup-deploy@$server";
 done
