changed running text and fixed bugs in deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -30,7 +30,7 @@ mkdir "$deployDir"
 for config in "$configDir"/*.config.dist.json; do
   # set token in config
   tempConfig="$(mktemp)"
-  jq ".api.authorization=\"$BEARER_TOKEN\"" "$config" > "$tempConfig" || die "Could not set \$BEARER_TOKEN in $config."
+  jq ".api.authorization=\"Bearer $BEARER_TOKEN\"" "$config" > "$tempConfig" || die "Could not set \$BEARER_TOKEN in $config."
   mv "$tempConfig" "$config"
 
   # derive name of this deploy from config file name
@@ -42,6 +42,8 @@ for config in "$configDir"/*.config.dist.json; do
 
   # copy files over
   cp --recursive "$targetDir"/* "$deploySubDir"
+
+  sed "s#<base href=\"/\" />#<base href=\"freiraumup/$deployName\"/>#g" "$deploySubdir/index.html" || die 1 "Could not change base href"
 
   # clone corresponding branch of ads repo to destination if ADS_REPO_URL is set
   if [ -n "$ADS_REPO_URL" ]; then
